### ISSUE TITLE
Mining Drill Issue

### ISSUE THREAD

**Issue by k1ndskopf** [TechReborn/StevesCarts#28] opened 2016-12-07 17:10 UTC
Hello, i built a card with the following setup
standard hull
solar engine
coal engine
basic drill
large railer
torch placer
bridge builder
internal storage x2
liquid sensors
height controller

i tried to sent him down to diamond level(i switched the height multiple times to try to solve the issue) but if i let him start at over 63 it will go to height 63 and then return to the cargo manager again and again

i tried to solve this problem with building the first tracks and the cargo manager at a level below 63 but if i do this it wont go deeper at all. it just drives the first track and instantly returns to the station...

**Comment by modmuss50** [comment] 2016-12-07 17:28
Ok thanks, when I get some time I will recreate your setup and see whats up.

**Comment by MyDaysBoy** [comment] 2017-04-27 17:05
I can confirm this bug as well. In more detail, it has been happening since at least 2.1.0.62 - After removing the material for the cart's current position, it removes the block right in front of the cart rather than placing a rail and moving forward. Since there is no rail in front, it heads back to the Cargo Manager. When returning the second and subsequent times, it sees the missing block and returns again - even with the bridge-builder upgrade which should just fill in the missing block and place a track. It seems that this only starts at level 62 - it digs down to 62 just fine, then at 62 starts removing that block in front and turning back. Operation above 62 seems okay. Lastly, if I fill in that missing block and throw a track down, when the cart returns it mines that position okay, then removes that block in front.

I'd have to stand there all day throwing down filler blocks and tracks for the cart to work for mining, so this bug makes a mining cart a useless feature.

**Comment by TheElectricCake** [comment] 2017-07-18 05:57
I am now seeing this bug happening in 1.12 with a cart which has
standard hull
coal engine
hardened drill
large railer
bridge builder
top storage
side storage
internal storage x2
liquid sensors

It will mine out a block right in front of and below itself (where the drill normally does not reach!), then turn around instead of filling it in using the bridge builder. It doesn't matter what I put in the bridge builder. If I fill in the hole, it will lay track, then it will dig a new hole in front of itself just as MyDaysBoy states.

**Comment by TheMrReal** [comment] 2017-07-23 17:43
I have a bug  on 1.11
he mine 3x3 but when he is 2 down of the cargo manager it will mine in the middle 1 more so that he cant place a track to keep mining so he go back and wait until the block is placed again but he mine that again so he cant keep mining until the diamond lager is. but on another world it work without something wrong

**Comment by goldspy98** [comment] 2017-08-05 18:32
I have the same bug on 1.12, I believe it is related to chunks (My cart has a chunk loader, I don't know if it is related), at least on mine when the cart reach a new chunk it breaks the block just in front rather than put a rail, now if you manually put a rail for him it will reach there but will do exactly the same as before, so as my experience for some reason the cart is only able to break blocks out of the chunk he was places, but for some reason it can't add blocks like rails.

Cart setup:
hardened drill
chunk loader
liquid sensors
height controller
...

Edit: Looks like it only happens when cart is minning down to reach the desired height, if you manually put the rail till the desired height it will work.

**Comment by nhayes-me** [comment] 2017-08-18 00:25
Can confirm on 1.12.  I can add some more.  Confirming Goldspy98 that it happens when the cart is mining down.  At level 63/62 the drill logic starts mining one extra block below normal right infront of the cart.  The cart then turns around and repeats the process.  If rail down along to the desired height is pre-placed the drill works as normal

**Comment by GoryMoon** [comment] 2018-01-14 21:04
Can anyone test if this is still a thing in the latest 1.12 version?

**Comment by Astewen** [comment] 2018-01-16 18:19
I just tested v2.4.16.81 in MC 1.12.2 and it's still not working. I started at y69 and told it to mine down to y52. It started digging and was fine until it hit y62 where it dug out the block at Y61 (where it should have placed the next rail). It turned around and did the same thing in the other direction.

**Comment by GoryMoon** [comment] 2018-01-16 20:22
What modules did you have in the cart?
As I can't reproduce this with the same modules listed in the first comment, started it at 87 and it went down to 9 as specified in the gui.

**Comment by Astewen** [comment] 2018-01-17 15:27
I had:

standard hull, coal engine, hardened drill, small railer, internal storage x2, torch placer

In case it might be a mod conflict, I removed all mods except:

	jei_1.12.2-4.8.0.114.jar
	RebornCore-1.12.2-3.4.11.153-universal.jar
	StevesCarts-1.12.2-2.4.16.81.jar
	Wawla-1.12.2-2.5.246.jar

I just ran some more tests and it is definitely intermittent and I cannot identify why/what is triggering it. In a new all-Plains world: My first tunnel, facing west did not work (from y69 to y57, same extra block-removal at y61), but when it turned around and went east it worked all the way down to y57. So I tried north and south... both worked. Thinking that west-facing was the issue I tried a west tunnel a couple of chunks away but it worked also! So, maybe it's not that west was the issue. I went back to the failed west, moved right (negative Z direction) 10 blocks and tried again, it failed again (so now only west-facing fails and only right here?). Next I moved 10 blocks to the other side of the original fail (positive Z direction) and this time it worked (now to the left of the original fail). Moved over 10 more in that direction and it worked again. So now I have 2 fails next to each other and 2 successes next to each other - and both of those sets side-by-side, mining in the same direction.

Very strange. All in the same world, same cart, same start y's and target y's. I checked the chunk boundaries and they don't seem to be a factor, all failed extra-block removals and and successes were away from the boundaries. All were in negative X, positive Z chunks, so I didn't cross any 0 datums either.

I wish I could give you more. I'm a programmer as well and this has me scratching my head.

**Comment by GoryMoon** [comment] 2018-01-17 15:53
Hm, Have to look into it some more and test more locations with debugging code.
It's indeed a strange issue.

**Comment by GoryMoon** [comment] 2018-06-11 17:31
Could this be tested with [this](https://jenkins.modmuss50.me/job/Team%20Reborn/job/StevesCarts/job/1.12/102/artifact/build/libs/StevesCarts-1.12.2-2.4.20.102.jar) version if it's still a problem, think I found the issue, would want some more testing done on it before release

**Comment by Nuchaz** [comment] 2018-06-15 21:32
I was experiencing this same issue in 1.12.2 using the FTB Continuum modpack. I tried the version linked above (StevesCarts-1.12.2-2.4.20.102) and it seems to have solved the problem.

**Comment by GoryMoon** [comment] 2018-06-15 22:05
Nice, it's just got released in a proper build to the public.
Will close this now.

**Closed by GoryMoon** 2018-06-15 22:05 UTC
Labels: Bug-major, Needs Validation, question
